### ISSUE TITLE
special (foreign) characters not displayed

### ISSUE THREAD

**Issue by mnul** [nplan/HomeButtons#14]
Hi, 
I've set up my 2 Home Buttons last night and found out, that the display cannot print special (foreign) characters (like ä ö ü ß). 
If you put those caracters into the button description the will not show at all. So instead "Büro" it will just print "Bro".

It would be helpful to have the entire ASCII Latin set. Emojis would be nice too!

**Comment by nplan** [comment]
Good point, will add in the future.

**Comment by nplan** [comment]
Fixed in v1.1.0.
