### ISSUE TITLE
Enhancement: show Device Name on Sensor value screen

### ISSUE THREAD

**Issue by gon0** [nplan/HomeButtons#17]
Hello everyone,

here is a proposal, you can decide if you want to implement it: I have 2 Homebuttons (maybe more in the future ;) ) and I would find it helpful, if the Device Name (e.g. HomeButtonsFDE97C) is shown on the E-Ink display in the same font size as e.g. "- Temp -" on the sensor value screen (holding one button > 4 seconds).
Especially if more than one Homebutton is used that are not mounted to a wall, it is helpful to put the buttons back to their place (especially if the Device Name contains information like "living room" or "kitchen").

**Comment by nplan** [comment]
Added in v2.0.1-beta.
