### ISSUE TITLE
[Case] Enhancement idea: add guided holes to reach buttons without disassembly

### ISSUE THREAD

**Issue by mcarbonne** [nplan/HomeButtons#20]
I received my "HomeButtons" today, a nicely built product !

I had an idea to improve the back plate design: add guides holes to reach reset and boot buttons:
![front_view](https://user-images.githubusercontent.com/46689813/216781865-f22afbab-8259-4df3-a055-1c0e06d6d6e5.png)
![back_view](https://user-images.githubusercontent.com/46689813/216781864-21349d5d-2d67-4dd3-9d7c-b5991a6f92ef.png)

Note: this is for illustration purpose only, I did not check dimensional accuracy at all.

Also, I noticed that step and STL files on github aren't up to date. I would be nice if you upload the last revision :pray:

**Comment by nplan** [comment]
Not needed, since the latest case version is much easier to open.
