### ISSUE TITLE
Nice to have: trigger MQTT autodiscovery / configuration menu

### ISSUE THREAD

**Issue by mcarbonne** [nplan/HomeButtons#24]
Currently, there is no way to trigger an MQTT autodiscovery message.
It would be nice to have a dedicated "config" menu, allowing to :
- trigger autodiscovery
- enter setup
- enter wifi setup
- perform a factory reset
- reboot ?
It might even replace the "10s/20s/30s" press behaviors.

This weekend, after an update of my MQTT broker, I had some issues with home assistant so I had to remove some devices.
It appears that there is currently no easy way to trigger the autodiscovery.
Looking at the code, I found only 2 methods:
- perform a factory reset
- update the firmware

**Comment by nplan** [comment]
The config menu is a great idea. Will implement in the future.

The autodiscovery message can actually be triggered this way:

1. Hold any button for 10s to enter setup
2. Immediately press a button to exit the setup
3. The autodiscovery message will be sent the next time network connects (either button press of timer wakeup)
