### ISSUE TITLE
[Feature] Allow to fix the font size

### ISSUE THREAD

**Issue by hilsonp** [nplan/HomeButtons#33]
I added a label on the six buttons. All have the same number of letters but the do not all have the same font size. 

This is weird and quite ugly. 

Can we get a bit more control on how labels are displayed ?

![image](https://user-images.githubusercontent.com/7338241/224863059-ae630f75-a234-4c9b-995b-33911a216e47.jpeg)

**Comment by mcarbonne** [comment]
In the meantime, you can trick the font size by adding white spaces at the beginning/end of labels.

**Comment by Zixim** [comment]
Fixed width font ?

**Comment by nplan** [comment]
I think adding some spaces at the back as @mcarbonne  suggested is the simplest solution here.
