### ISSUE TITLE
[Feature] Status page

### ISSUE THREAD

**Issue by joergkrainer** [nplan/HomeButtons#36]
Hi,

it would be nice if we can have status pages if powered with usb etc.
and closable with one of the buttons? 

Usecases are messages from dish washer etc. 

What do you think about it?

best, Jörg

**Comment by nplan** [comment]
I could make Home Buttons listen to a specific MQTT topic, and display a message when it arrives. Is this what you had in mind?

**Comment by joergkrainer** [comment]
Hi, yes - sounds great ;-)

**Comment by nplan** [comment]
Added in release v2.2.0.

Documentation: https://docs.home-buttons.com/original/user_guide/#custom_message

Note: Line breaks must be added in the message. Device will not split it automatically.
