### ISSUE TITLE
Availability of HomeButtons to buy

### ISSUE THREAD

**Issue by gon0** [nplan/HomeButtons#44]
Dear @nplan, 
you convinced me with your great product and I would like to buy more 😁 
The availability in Tindie is only one pcs. The link to Lectrons (https://docs.home-buttons.com/#where-to-get) is not actual, but on lectronz, the availability is zero.

For me it is not urgent. Will there be more devices available soon? It would be ok for me to preorder, so you can plan ahead.

Keep up your great work! :)

**Comment by nplan** [comment]
I'm glad to hear that. 🙂 Thanks for your interest.

More will be available in about a month. Preorders are unfortunately not possible at the moment.

**Comment by gon0** [comment]
Very well! I am glad to hear you are keeping up your good work and support! 

I'll check back in a month :)
