### ISSUE TITLE
Configure MDI icons using home assistant: label is too long

### ISSUE THREAD

**Issue by MatthiasLohr** [nplan/HomeButtons#47]
Great feature to allow MDI icons!!! Fantastic!!! Thanks!

Anyway, sorry for bothering again, but I think I found an issue here... When configuring the labels using Home Assistant, I'm getting an error: "Value mdi:account-plus2 for text.home_buttons_xxxxxx_button_1_label is too long (maximum length 15)". Is this limit coming from Home Assistant or somewhere from the device firmware?

**Comment by nplan** [comment]
That's the old limit... I guess MQTT discovery config wasn't updated correctly. Please restart the device using the settings [menu](https://docs.home-buttons.com/user_guide/#settings). Then press any button and the MQTT discovery config will be sent again. If it doesn't work then reboot Home Assistant & MQTT broker.

**Comment by MatthiasLohr** [comment]
That did the trick, thanks!

Maybe that would be a good entry for something like a "Troubleshooting"/"FAQ" section in the docs?
