### ISSUE TITLE
Text size

### ISSUE THREAD

**Issue by JunghaJungha** [nplan/HomeButtons#51]
Hi.

I love the new feature of icons in combination with text. But as the text size depends on the length of the text, it makes my display a bit messy.

It would be great if the text size could be the same size independent of the length when the a button label is mixed. 
It actually means the font should be always the smaller font in mixed mode.

Thanks.

**Comment by nplan** [comment]
Hi, could you post a picture?

**Comment by JunghaJungha** [comment]
![20230606_204920](https://github.com/nplan/HomeButtons/assets/73291364/0f8bd587-e192-46f8-90f2-0716bd6909f7)
![20230606_205045](https://github.com/nplan/HomeButtons/assets/73291364/5c61a816-6d82-4803-8968-00a6049c8c41)
Please see here both pictures, where I force one to be small by underscore

**Comment by nplan** [comment]
Added option to force small font by prepending an underscore in v2.2.1.

**Comment by JunghaJungha** [comment]
Thank you, works like a charm
