### ISSUE TITLE
Custom message not being displayed

### ISSUE THREAD

**Issue by NiccyB** [nplan/HomeButtons#54]
I have tried to use the custom message as per https://docs.home-buttons.com/mini/user_guide/#custom_message but this appears not to work - i.e. no message is displayed when a button is pressed after the (retained) message is published.

**Comment by nplan** [comment]
Documentation error, sorry.

The correct topic is `{base_topic}/{device_name}/cmd/disp_msg`.

**Comment by NiccyB** [comment]
No problem.
How do I put a line break in the text? If I use the custom message "Custom message", it's all at the top of the screen and displays as "Custom mes" - i.e. it doesn't wrap.
I've tried the obvious "\n".

**Comment by NiccyB** [comment]
Entirely my fault - wrong use of '\n'!

I was using

mosquitto_pub -h '127.0.0.1' -t 'homebuttons/HB699172/cmd/disp_msg' -m 'Custom\nmessage' -r

When I should have used

mosquitto_pub -h '127.0.0.1' -t 'homebuttons/HB699172/cmd/disp_msg' -m $'Custom\nmessage' -r

Apologies and thank you.
