### ISSUE TITLE
Possible to accidentally reset too easily.

### ISSUE THREAD

**Issue by NiccyB** [nplan/HomeButtons#55]
Home Buttons Mini

To display sensor data, hold down any button for 3 seconds. Keep that button pressed for a further 3 seconds and the management screen is displayed.

The problem is that it takes just over a second for the screen to re-draw which means if you're waiting for the screen to finish re-drawing before releasing the button, it's easy to press a button for the full five seconds required for the management screen.

Once you're at the management screen, there is no obvious way to exit (yes, I know how because I've used the manual, but see this from the point of view of a user in the same household who hasn't). From here, pressing the 'WiFi Setup' button makes the whole switch non-functional until somebody who knows how resets the WiFi details.

I think what I'm asking for is a way of making the whole unit less susceptible to people messing about with the configuration.

**Comment by nplan** [comment]
In v2.3.0 the settings menu must now be opened by holding two buttons simultaneously for 5 s.
