### ISSUE TITLE
Live information on screen

### ISSUE THREAD

**Issue by zoic21** [nplan/HomeButtons#6]
Hello,
Did you plan to add the capacity of live information on screen ? To preserve battery device can connect every 10 min to Mqtt and read retain topic with information to display (home mode, ext temp, alarm mode...)

Thank in advance for your reply

**Comment by nplan** [comment]
Currently that is not implemented. But I'm open to suggestions what to add in the future.

As I see it, the main problem with displaying other info on the screen is that it covers button labels, which are the main feature of the device.

I was thinking of maybe adding the possibility of displaying some data at the top and then only have labels for the bottom 4 buttons.

What do you think about this?

**Comment by zoic21** [comment]
Hello,

It can be amazing and very useful, with this two line we can display information like home mode and ext temp.

**Comment by zoic21** [comment]
Hello,
I got an idea for this request. Maybe it's possible to use "scroll" information for top of device. For exemple we can send this retain topic on mqtt : 
```
[
{"line_1" : "Mode","line_2" : "Night"},
{"line_1" : "Ext","line_2" : "17°C"},
{"line_1" : "Int","line_2" : "21°C"}
]
```

And on home buttons we can used 2 first button to scroll between information (for exemple : Mode Night then Ext 17°C then Int 21°C), other 4 button leave like actually.

I don't realize how difficult it is to code this, but I think it can be usefull

**Comment by nplan** [comment]
Will add something like this, thanks for your feedback!

**Comment by MiCkSoftware** [comment]
Hi all,
Another idea on the same topic : if there was a rest API or MQTT topic to update buttons label it would then be possible to change display on button click and open a lot of possibilities (like using two buttons to scroll trough multiple screens, ...)
Cheers !

**Comment by EarMaster** [comment]
The ability to change the labels without entering setup mode would be a great addition. This would allow a lot more flexible usage. Of course battery life will go down significantly when there are regular updates to the screen, but this would be something everybody has to decide for themselves.

**Comment by nplan** [comment]
Sure, changing labels via MQTT is definitely on the list. The new label message can be posted with retain flag and the label will change in 10 minutes at the latest, when it wakes up for sensor reporting. Or right after a button press.

I'll also make the 10 minute wake up interval user adjustable.

**Comment by AndersNielsenUFST** [comment]
Thumbs up on this one. I am thinking of a scenario where you click "Activate Alarm" and the display text changes to "Windows are open".

**Comment by Hamsterman** [comment]
Thumbs on this one. I am thinking of a scenario where you click "Activate Alarm" and the text changes to "Windows are open"

**Comment by zoic21** [comment]
Hello,
I just update to last firmware, it's perfectly work !!!! Thank a lot for this update
