### ISSUE TITLE
Update from v2.3.0 to v2.4.0 on original HomeButtons does not work using Online Flasher

### ISSUE THREAD

**Issue by daj102** [nplan/HomeButtons#60]
Title basically says it all; I have a v2.3 original Home Buttons device, and just tried to update from v2.3.0 firmware to v2.4.0 firmware using the Online Flasher tool.  The device went into boot mode fine, was recognized on my computer, connected, went through the motions of flashing - but when it was rebooted, it still showed v2.3.0 in the screen and in HomeAssistant.

A full image flash using the same tool worked fine, however - I did also click erase image, so I had to reconfigure.  Device is working fine.

**Comment by nplan** [comment]
This is as expected. Only full image can be used. I edited the release notes to make it clearer.
