### ISSUE TITLE
special chars limitations?

### ISSUE THREAD

**Issue by antonpiatek** [nplan/HomeButtons#65]
I'm trying to show the batter percentage on the screen - if I just publish it as a big text on its own `82%` then it renders find. However small text `_82%` and icons `mdi:lightbulb 82%` (or `mdi:lightbulb _82%`) seem to not render the `%` symbol.

Is this a limitation of special char rendering? Or should this work?

**Comment by nplan** [comment]
Seems to be a font bug. Both the big and the small font have the same character set, but % is not being rendered for the small one apparently. Other special characters work fine. No easy solution at the moment unfortunately.

**Comment by nplan** [comment]
Fixed in v2.4.1.
