### ISSUE TITLE
Need support for recovering my bricked Home Buttons after update

### ISSUE THREAD

**Issue by db-it** [nplan/HomeButtons#69]
I didn't found another way to contact, so I try this one.

I updated my Home Buttons device from v2.0.4 directly to v2.4.1. I missed the hint, that this direct update will brick my device. 
So I followed the manual (https://docs.home-buttons.com/help/) section 5. Bricked device. I managed to proceed to step 13. But I'm struggling with step "14. In the first offset field enter 9000 and choose the provided NVS bin file." **What is the "NVS bin file"** and where can I get it?
I searched the web for "NVS bin file", but found nothing helpful. Also the manual doesn't mention it.

Can someone please help me?

**Comment by nplan** [comment]
The NVS bin file is specific to your device. Please write an email with the serial number to support@home-buttons.com. I'll reply with the file attached.

The help appears to be missing this info, sorry.
