### ISSUE TITLE
Flickering while updating

### ISSUE THREAD

**Issue by Hamsterman** [nplan/HomeButtons#77]
I have had my HomeButtons a week or so and is just playing around with it so far.

What I do notice that each time it does an update (not me pressing a button) the screen flickers black/white for about 1 second.
Is this intended behavior? (it does not look great)

**Comment by Zixim** [comment]
That's inherent to e-ink displays. It's due to the low refresh rate. The refresh rate is so low that you can clearly notice the screen flashing/refreshing.
On the bright side, e-ink displays consume near-zero power while displaying information.

**Comment by Hamsterman** [comment]
Closed based on @Zixim comment
